#!/bin/bash
#
# mongo-connector               Start Mongo Connector
#
# chkconfig: 345 90 25
# description: Mongo Connector replicates data from MongoDB to external
#              database systems.

### BEGIN INIT INFO
# Provides: mongo-connector
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Required-Start:
# Required-Stop:
# Short-Description: Start up Mongo Connector
# Description: Mongo Connector replicates data from MongoDB to external
#              database systems.
### END INIT INFO

# source function library
DEBIAN=
if [ -f /lib/lsb/init-functions ]; then
    DEBIAN=1
    . /lib/lsb/init-functions
else
    . /etc/rc.d/init.d/functions
fi

RETVAL=0

db_name=$2
pidfile=/var/run/mongo-connector/mc_$db_name.pid
base_config=/etc/mongo-connector/base.json
config_dir=/etc/mongo-connector/config
error=/var/log/mongo-connector/mongo-connector_$db_name.err
workdir=/var/run/mongo-connector

config=$workdir/"$db_name.json"
oplog=$workdir/"$db_name.oplog"

mc="python -m mongo_connector.connector \
    -c $config -o $oplog >/dev/null 2> $error & \
    echo "'$!'" > $pidfile"


jq_merge()
{
    jq -s '.[0] + .[1]' $1 $2
}

start()
{
    if [ -z "$1" ]; then
        echo "Using configuration " $base_config
    else
        echo "Merging base configuration"
        jq_merge "$base_config" $config_dir/"$1.json" > $config
    fi

    echo "starting mongo-connector "
    if [ "$DEBIAN" ]; then
	/sbin/start-stop-daemon --start --exec /bin/sh -p $pidfile -- -c "$mc"
    else
	daemon --pidfile $pidfile "$mc"
    fi

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo "done."
    else
        echo "failed. Please check exit code and logs for more information"
    fi

    return $RETVAL
}

stop()
{
    echo "stopping mongo-connector: "
    killproc -p $pidfile

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo "done."
        rm -f $config
        rm -f $lockfile
    else
        echo "failed. Please check exit code and logs for more information"
    fi
    return $RETVAL
}

restart() {
    $0 stop
    $0 start
}

check_status() {
    if [ "$DEBIAN" ]; then
	echo -n "mongo-connector "
	status_of_proc -p $pidfile mongo-connector
    else
	status -p $pidfile mongo-connector
    fi
}

case "$1" in
    start)
        start $2
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
	check_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        RETVAL=2
esac
exit $RETVAL
